server:
  port: 9090
spring:
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    function:
      definitions: consumer
    stream:
      binders:
        kafka:
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    bindings:
                      producer-partition-expression-out-0:
                        producer:
                          configuration:
                            value.serializer: org.apache.kafka.common.serialization.StringSerializer
                            linger.ms: 0
#      output-bindings: producer-partition-expression-out-0
      bindings:
        producer-partition-expression-out-0:
          destination: destination.topic
          content-type: text/plain
          producer:
            partition-key-expression: headers['partitionKey']
            use-native-encoding: true
            partition-count: 10
        consumer-in-0:
          destination: destination.topic      